package views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controls.Control;

import javax.swing.*;
import java.awt.*;

import static models.View.*;

public class MainView extends JFrame {
    private JPanel panel;
    private JButton alunoViewButton;
    private JButton cursoViewButton;
    private JButton professorViewButton;
    private JButton turmaViewButton;
    private JButton matriculaViewButton;
    private JButton notasButton;

    public MainView(Control control) {
        super("Program");
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setContentPane(panel);
        this.setSize(300, 300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        ImageIcon icon = new ImageIcon("src/main/images/icon.png");
        this.setIconImage(icon.getImage());

        alunoViewButton.addActionListener(e -> control.changeView(ALUNO_VIEW));
        cursoViewButton.addActionListener(e -> control.changeView(CURSO_VIEW));
        professorViewButton.addActionListener(e -> control.changeView(PROFESSOR_VIEW));
        turmaViewButton.addActionListener(e -> control.changeView(TURMA_VIEW));
        matriculaViewButton.addActionListener(e -> control.changeView(MATRICULA_VIEW));
        notasButton.addActionListener(e -> control.changeView(NOTAS_VIEW));
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(6, 1, new Insets(10, 10, 10, 10), -1, -1));
        panel.setBackground(new Color(-13487566));
        alunoViewButton = new JButton();
        alunoViewButton.setBorderPainted(true);
        alunoViewButton.setContentAreaFilled(true);
        alunoViewButton.setFocusPainted(false);
        alunoViewButton.setOpaque(true);
        alunoViewButton.setText("Alunos");
        panel.add(alunoViewButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                       GridConstraints.FILL_HORIZONTAL,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cursoViewButton = new JButton();
        cursoViewButton.setText("Cursos");
        panel.add(cursoViewButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                       GridConstraints.FILL_HORIZONTAL,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        professorViewButton = new JButton();
        professorViewButton.setText("Professores");
        panel.add(professorViewButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                           GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        matriculaViewButton = new JButton();
        matriculaViewButton.setFocusPainted(false);
        matriculaViewButton.setText("Matriculas");
        panel.add(matriculaViewButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                           GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
        turmaViewButton = new JButton();
        turmaViewButton.setText("Turmas");
        panel.add(turmaViewButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                       GridConstraints.FILL_HORIZONTAL,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        notasButton = new JButton();
        notasButton.setFocusPainted(false);
        notasButton.setText("Notas");
        panel.add(notasButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                   GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }

}
