package views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controls.Control;
import models.entitys.Aluno;
import models.entitys.Turma;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.stream.Collectors;

import static models.Estado.FECHADA;
import static models.Format.decimalMask;
import static models.View.MAIN_VIEW;

public class NotasView extends JFrame {
    private final Control control;
    private JPanel panel;
    private JComboBox<Turma> turma;
    private JComboBox<Aluno> aluno;
    private JFormattedTextField nota;
    private JButton fecharTurmaButton;
    private JButton salvarNotaButton;

    public NotasView(Control control) {
        super("Notas");
        this.control = control;
        $$$setupUI$$$();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setContentPane(panel);
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);

        turma.addActionListener(e -> populateAlunos());
        salvarNotaButton.addActionListener(e -> control.setNota());
        fecharTurmaButton.addActionListener(e -> control.closeTurma());
    }

    @Override
    public void dispose() {
        control.changeView(MAIN_VIEW);
        super.dispose();
    }

    private void populateAlunos() {
        Turma turma = (Turma) this.turma.getSelectedItem();
        if (turma != null) {
            List<Aluno> alunos = control.getTurmaControl().getAlunos(turma.getId());
            DefaultComboBoxModel<Aluno> alunoModel = new DefaultComboBoxModel<>();
            alunoModel.addAll(alunos);
            this.aluno.setModel(alunoModel);

            boolean bool = control.getTurmaControl().containsNullNotas(turma.getId());
            fecharTurmaButton.setEnabled(! bool);
        }
    }

    public Turma getTurma() { return (Turma) turma.getSelectedItem(); }

    public Aluno getAluno() { return (Aluno) aluno.getSelectedItem(); }

    public String getNota() { return nota.getText(); }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), - 1, - 1));
        panel.setBackground(new Color(- 13487566));
        panel.add(turma, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(- 1, 30), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(- 3618616));
        label1.setText("Aluno");
        panel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(- 3618616));
        label2.setText("Turma");
        panel.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(- 3618616));
        label3.setText("Nota");
        panel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(aluno, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(- 1, 30), null, 0, false));
        panel.add(nota, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(- 1, 30), null, 0, false));
        fecharTurmaButton = new JButton();
        fecharTurmaButton.setEnabled(false);
        fecharTurmaButton.setFocusPainted(false);
        fecharTurmaButton.setText("Fechar Turma");
        panel.add(fecharTurmaButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(- 1, 30), null, 0, false));
        salvarNotaButton = new JButton();
        salvarNotaButton.setFocusPainted(false);
        salvarNotaButton.setText("Salvar Nota");
        panel.add(salvarNotaButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(- 1, 30), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        nota = new JFormattedTextField(decimalMask);

        turma = new JComboBox<>();
        List<Turma> turmas = control.getTurmaControl().getAll().stream().filter(t -> t.getEstado() != FECHADA).collect(Collectors.toList());
        DefaultComboBoxModel<Turma> turmaModel = new DefaultComboBoxModel<>();
        turmaModel.addAll(turmas);
        turma.setModel(turmaModel);
        turma.setSelectedItem(null);

        aluno = new JComboBox<>();
        this.populateAlunos();
    }

    public void clearFields() {
        turma.setSelectedItem(null);
        aluno.setSelectedItem(null);
        nota.setValue(null);
    }
}
