package views.cells;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.entitys.Curso;

import javax.swing.*;
import java.awt.*;

public class CursoCell implements ListCellRenderer<Curso> {
    private JPanel panel;
    private JLabel id;
    private JLabel nome;
    private JLabel sigla;
    private JLabel cargaHoraria;

    @Override
    public Component getListCellRendererComponent(JList<? extends Curso> list, Curso value, int index, boolean isSelected, boolean cellHasFocus) {
        id.setText(String.valueOf(value.getId()));
        nome.setText(value.getNome());
        sigla.setText(value.getSigla());
        cargaHoraria.setText(String.valueOf(value.getCargaHoraria()));
        if (isSelected) {
            panel.setBackground(list.getSelectionBackground());
            panel.setForeground(list.getSelectionForeground());
        } else {
            panel.setBackground(list.getBackground());
            panel.setForeground(list.getForeground());
        }
        return panel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FormLayout("center:50pt:noGrow,left:4dlu:noGrow,center:150pt:noGrow,left:4dlu:noGrow,center:100pt:noGrow,left:4dlu:noGrow,center:50pt:noGrow", "fill:13px:grow"));
        panel.setBackground(new Color(- 13487566));
        panel.setPreferredSize(new Dimension(- 1, 30));
        id = new JLabel();
        id.setForeground(new Color(- 3618616));
        id.setText("Label");
        CellConstraints cc = new CellConstraints();
        panel.add(id, cc.xy(1, 1));
        nome = new JLabel();
        nome.setForeground(new Color(- 3618616));
        nome.setText("Label");
        panel.add(nome, cc.xy(3, 1));
        sigla = new JLabel();
        sigla.setForeground(new Color(- 3618616));
        sigla.setText("Label");
        panel.add(sigla, cc.xy(5, 1));
        cargaHoraria = new JLabel();
        cargaHoraria.setForeground(new Color(- 3618616));
        cargaHoraria.setText("Label");
        panel.add(cargaHoraria, cc.xy(7, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }

}
