package views.cells;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.entitys.Curso;

import javax.swing.*;
import java.awt.*;

public class CursoCell implements ListCellRenderer<Curso> {
    private JPanel panel;
    private JLabel id;
    private JLabel nome;
    private JLabel sigla;
    private JLabel cargaHoraria;

    @Override
    public Component getListCellRendererComponent(final JList<? extends Curso> list, final Curso value, final int index, final boolean isSelected, final boolean cellHasFocus) {
        final String id = String.valueOf(value.getId());
        final String nome = value.getNome();
        final String sigla = value.getSigla();
        final String cargaHoraria = String.valueOf(value.getCargaHoraria());
        this.id.setText(id);
        this.nome.setText(nome);
        this.sigla.setText(sigla);
        this.cargaHoraria.setText(cargaHoraria);
        if (isSelected) {
            this.panel.setBackground(list.getSelectionBackground());
            this.panel.setForeground(list.getSelectionForeground());
        } else {
            this.panel.setBackground(list.getBackground());
            this.panel.setForeground(list.getForeground());
        }
        return this.panel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FormLayout("center:50px:grow,left:4dlu:noGrow,center:250px:grow,left:4dlu:noGrow,center:50px:grow,left:4dlu:noGrow,center:50px:grow", "fill:13px:grow"));
        panel.setBackground(new Color(- 13487566));
        panel.setPreferredSize(new Dimension(- 1, 30));
        id = new JLabel();
        id.setForeground(new Color(- 3618616));
        id.setText("ID");
        CellConstraints cc = new CellConstraints();
        panel.add(id, cc.xy(1, 1));
        nome = new JLabel();
        nome.setForeground(new Color(- 3618616));
        nome.setText("Nome");
        panel.add(nome, cc.xy(3, 1));
        sigla = new JLabel();
        sigla.setForeground(new Color(- 3618616));
        sigla.setText("Sigla");
        panel.add(sigla, cc.xy(5, 1));
        cargaHoraria = new JLabel();
        cargaHoraria.setForeground(new Color(- 3618616));
        cargaHoraria.setText("Carga Horária");
        panel.add(cargaHoraria, cc.xy(7, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }
}
