package views.cells;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.entitys.Matricula;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

import static models.Format.dateFormatter;

public class MatriculaCell implements ListCellRenderer<Matricula> {
    private JPanel panel;
    private JLabel aluno;
    private JLabel turma;
    private JLabel dataMatricula;
    private JLabel nota;
    private JLabel situacao;
    private JLabel curso;

    @Override
    public Component getListCellRendererComponent(final JList<? extends Matricula> list, @NotNull final Matricula value, final int index, final boolean isSelected, final boolean cellHasFocus) {
        final String aluno = value.getAluno().getNome();
        final String turma = String.valueOf(value.getTurma().getId());
        final String curso = value.getTurma().getCurso().getSigla();
        final String dataMatricula = value.getDataMatricula().format(dateFormatter);
        final String nota = value.getNota() == null ? "--" : String.valueOf(value.getNota());
        final String situacao = value.getSituacao();
        this.aluno.setText(aluno);
        this.turma.setText(turma);
        this.curso.setText(curso);
        this.dataMatricula.setText(dataMatricula);
        this.nota.setText(nota);
        this.situacao.setText(situacao);
        if (isSelected) {
            this.panel.setBackground(list.getSelectionBackground());
            this.panel.setForeground(list.getSelectionForeground());
        } else {
            this.panel.setBackground(list.getBackground());
            this.panel.setForeground(list.getForeground());
        }
        return this.panel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        this.$$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FormLayout("center:200px:grow,left:4dlu:noGrow,center:50px:grow,left:4dlu:noGrow,center:50px:noGrow,left:4dlu:noGrow,center:100px:grow,left:4dlu:noGrow,center:50px:grow,left:4dlu:noGrow,center:100px:grow", "center:d:grow"));
        panel.setBackground(new Color(- 13487566));
        panel.setPreferredSize(new Dimension(- 1, 30));
        aluno = new JLabel();
        aluno.setForeground(new Color(- 3618616));
        aluno.setText("Aluno");
        CellConstraints cc = new CellConstraints();
        panel.add(aluno, cc.xy(1, 1));
        turma = new JLabel();
        turma.setForeground(new Color(- 3618616));
        turma.setText("Turma");
        panel.add(turma, cc.xy(3, 1));
        dataMatricula = new JLabel();
        dataMatricula.setForeground(new Color(- 3618616));
        dataMatricula.setText("Data deMatrícula");
        panel.add(dataMatricula, cc.xy(7, 1));
        nota = new JLabel();
        nota.setForeground(new Color(- 3618616));
        nota.setText("Nota");
        panel.add(nota, cc.xy(9, 1));
        situacao = new JLabel();
        situacao.setForeground(new Color(- 3618616));
        situacao.setText("Situação");
        panel.add(situacao, cc.xy(11, 1));
        curso = new JLabel();
        curso.setForeground(new Color(- 3618616));
        curso.setText("Curso");
        panel.add(curso, cc.xy(5, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }
}
