package views.cells;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.Format;
import models.entitys.Matricula;

import javax.swing.*;
import java.awt.*;

import static models.Format.dateFormatter;

public class MatriculaCell implements ListCellRenderer<Matricula> {
    private JPanel panel;
    private JLabel aluno;
    private JLabel turma;
    private JLabel dataMatricula;
    private JLabel nota;

    @Override
    public Component getListCellRendererComponent(JList<? extends Matricula> list, Matricula value, int index, boolean isSelected, boolean cellHasFocus) {
        String aluno = value.getAluno().getNome();
        String turma = String.valueOf(value.getTurma().getId());
        String dataMatricula = value.getDataMatricula().format(dateFormatter);
        String nota = String.valueOf(value.getNota());
        this.aluno.setText(aluno);
        this.turma.setText(turma);
        this.dataMatricula.setText(dataMatricula);
        this.nota.setText(nota);
        if (isSelected) {
            panel.setBackground(list.getSelectionBackground());
            panel.setForeground(list.getSelectionForeground());
        } else {
            panel.setBackground(list.getBackground());
            panel.setForeground(list.getForeground());
        }
        return panel;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FormLayout("center:d:grow,left:4dlu:noGrow,center:d:grow,left:4dlu:noGrow,center:d:grow,left:4dlu:noGrow,center:d:grow", "center:d:grow"));
        panel.setPreferredSize(new Dimension(- 1, 30));
        aluno = new JLabel();
        aluno.setForeground(new Color(- 3618616));
        aluno.setText("Label");
        CellConstraints cc = new CellConstraints();
        panel.add(aluno, cc.xy(1, 1));
        turma = new JLabel();
        turma.setForeground(new Color(- 3618616));
        turma.setText("Label");
        panel.add(turma, cc.xy(3, 1));
        dataMatricula = new JLabel();
        dataMatricula.setForeground(new Color(- 3618616));
        dataMatricula.setText("Label");
        panel.add(dataMatricula, cc.xy(5, 1));
        nota = new JLabel();
        nota.setForeground(new Color(- 3618616));
        nota.setText("Label");
        panel.add(nota, cc.xy(7, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }

}
