package ciu;

import cci.ControladorPrincipal;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class JanPrincipal extends JFrame {
	private       JPanel               mainPanel;
	private       JButton              cadastrarCursoButton;
	private final ControladorPrincipal controlador;

	public JanPrincipal(ControladorPrincipal controlador) {
		super("App");
		super.setDefaultCloseOperation(EXIT_ON_CLOSE);
		super.setContentPane(mainPanel);
		super.setSize(400, 400);
		super.setResizable(false);

		this.controlador = controlador;
		cadastrarCursoButton.addActionListener(e -> controlador.exibirJanCadCurso());
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.setBackground(new Color(-14803426));
		cadastrarCursoButton = new JButton();
		cadastrarCursoButton.setBackground(new Color(-11513776));
		cadastrarCursoButton.setBorderPainted(false);
		cadastrarCursoButton.setFocusPainted(false);
		cadastrarCursoButton.setForeground(new Color(-3289651));
		cadastrarCursoButton.setText("Cadastrar Curso");
		mainPanel.add(cadastrarCursoButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		mainPanel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() {return mainPanel;}

}
